DISABLE_LINTERS:
  - SPELL_CSPELL
  - PYTHON_PYLINT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT

REPOSITORY_KICS_CONFIG_FILE: kics-config.yml
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
